# -*- coding: utf-8 -*-
"""Fake_News.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-FjWXn2TnilM0MTv48d8WOiDwQCbG_dX
"""

!pip install transformers scikit-learn

import pandas as pd
import numpy as np
import torch

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

from transformers import BertTokenizer, BertForSequenceClassification
from transformers import Trainer, TrainingArguments

from google.colab import files
uploaded = files.upload()

import zipfile

with zipfile.ZipFile("archive (7).zip", 'r') as zip_ref:
    zip_ref.extractall("data")

fake = pd.read_csv("data/Fake.csv")
real = pd.read_csv("data/True.csv")

fake['label'] = 0
real['label'] = 1

df = pd.concat([fake, real], axis=0)
df = df.drop_duplicates()
df = df.sample(frac=1).reset_index(drop=True)

df['content'] = df['title'] + " " + df['text']

X_train, X_test, y_train, y_test = train_test_split(
    df['content'], df['label'], test_size=0.2, random_state=42
)

vectorizer = TfidfVectorizer(max_features=5000)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

model_nb = MultinomialNB()
model_nb.fit(X_train_vec, y_train)

y_pred = model_nb.predict(X_test_vec)

print(classification_report(y_test, y_pred))

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

train_encodings = tokenizer(list(X_train), truncation=True, padding=True, max_length=128)
test_encodings = tokenizer(list(X_test), truncation=True, padding=True, max_length=128)

class NewsDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = list(labels)

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = NewsDataset(train_encodings, y_train)
test_dataset = NewsDataset(test_encodings, y_test)

model = BertForSequenceClassification.from_pretrained(
    'bert-base-uncased',
    num_labels=2
)

model.to(device)

from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = logits.argmax(axis=1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='binary')
    acc = accuracy_score(labels, preds)
    return {"accuracy": acc, "f1": f1}

training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=1,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    logging_dir='./logs'
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

trainer.train()

trainer.evaluate()

from google.colab import drive
drive.mount('/content/drive')

model.save_pretrained("/content/drive/MyDrive/bert_model")
tokenizer.save_pretrained("/content/drive/MyDrive/bert_model")

print(df.duplicated().sum())

!pip install gradio

import gradio as gr
import torch
from transformers import BertTokenizer, BertForSequenceClassification

# Load model
model = BertForSequenceClassification.from_pretrained("bert_model")
tokenizer = BertTokenizer.from_pretrained("bert_model")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()
def predict_news(text):
    # mimic training format (IMPORTANT)
    text = "News: " + text

    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True).to(device)
    outputs = model(**inputs)

    probs = torch.nn.functional.softmax(outputs.logits, dim=1)[0]

    fake_prob = probs[0].item()
    real_prob = probs[1].item()

    if abs(fake_prob - real_prob) < 0.15:
        pred_text = "UNCERTAIN (model confused)"
    else:
        pred = "REAL" if real_prob > fake_prob else "FAKE"
        pred_text = f"""
Prediction: {pred}

Fake Score: {fake_prob:.2f}
Real Score: {real_prob:.2f}

⚠️ Model shows bias due to dataset distribution
"""
    return pred_text

interface = gr.Interface(fn=predict_news, inputs="text", outputs="text", title="Fake News Detector")
interface.launch()

# Test REAL samples from dataset
for i in range(3):
    text = df[df['label'] == 1]['content'].iloc[i]
    print("\n=== REAL SAMPLE ===")
    print(text[:200])
    print(predict_news(text))

# Test FAKE samples from dataset
for i in range(3):
    text = df[df['label'] == 0]['content'].iloc[i]
    print("\n=== FAKE SAMPLE ===")
    print(text[:200])
    print(predict_news(text))