# -*- coding: utf-8 -*-
"""Fake_News_Demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IM2Z_1Vl5UnJQ6qtRm4Z7nLy1gJLDJhz
"""

from google.colab import drive
drive.mount('/content/drive')

from transformers import BertTokenizer, BertForSequenceClassification
import torch

model_path = "/content/drive/MyDrive/bert_model"

model = BertForSequenceClassification.from_pretrained(model_path)
tokenizer = BertTokenizer.from_pretrained(model_path)

model.eval()

def predict_news(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)
    outputs = model(**inputs)
    probs = torch.softmax(outputs.logits, dim=1)

    fake_score = probs[0][0].item()
    real_score = probs[0][1].item()

    label = "FAKE" if fake_score > real_score else "REAL"

    return f"""
Prediction: {label}

Fake Score: {fake_score:.2f}
Real Score: {real_score:.2f}
"""

print(predict_news("Breaking: Scientists confirm humans can live without food for 2 months."))
print(predict_news("WASHINGTON (Reuters) - The U.S. Senate passed a new infrastructure bill after weeks of debate among lawmakers."))
print(predict_news("NEW DELHI - The Indian government introduced new policies to strengthen digital payment systems and improve financial inclusion across rural areas."))

import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import gradio as gr

# Load model from Google Drive
model_path = "/content/drive/MyDrive/bert_model"

tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForSequenceClassification.from_pretrained(model_path)

model.eval()

# Prediction function
def predict_news(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)

    with torch.no_grad():
        outputs = model(**inputs)
        probs = torch.softmax(outputs.logits, dim=1)

    fake_score = probs[0][0].item()
    real_score = probs[0][1].item()

    if real_score > fake_score:
        prediction = "REAL"
    else:
        prediction = "FAKE"

    return f"Prediction: {prediction}\n\nFake Score: {fake_score:.4f}\nReal Score: {real_score:.4f}"

# UI using Blocks (better layout)
with gr.Blocks() as demo:
    gr.Markdown("# 📰 Fake News Detection using BERT")

    with gr.Row():
        input_text = gr.Textbox(
            lines=8,
            label="Enter News Text",
            placeholder="Type or paste news article here..."
        )

    with gr.Row():
        output_text = gr.Textbox(
            lines=6,
            label="Prediction Result"
        )

    btn = gr.Button("Check News")

    btn.click(fn=predict_news, inputs=input_text, outputs=output_text)

demo.launch(share=True)